"""Generate bugs/INDEX.md from the BUG-*.md RCA files.

The bugs index used to live as a hand-maintained table inside bugs/README.md, so
the README churned on every new bug. This generator derives the listing from the
files themselves (the directory IS the source of truth), writes it to bugs/INDEX.md,
and leaves README.md stable. A forcing-function test
(tests/v2/test_bug_index_current.py) fails the build if INDEX.md is stale.

Usage:
    python tools/gen_bug_index.py            # rewrite bugs/INDEX.md
    python tools/gen_bug_index.py --check    # exit 1 if INDEX.md is out of date
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

BUGS_DIR = Path(__file__).resolve().parents[1] / "bugs"
INDEX_PATH = BUGS_DIR / "INDEX.md"

_NUM_RE = re.compile(r"BUG-(\d+)", re.IGNORECASE)
_TITLE_RE = re.compile(r"^#\s*BUG-\d+:\s*(.+?)\s*$", re.MULTILINE)
_SEVERITY_RE = re.compile(r"-\s*\*\*Severity:\*\*\s*(.+?)\s*$", re.MULTILINE)
_STATUS_RE = re.compile(r"-\s*\*\*Status:\*\*\s*(.+?)\s*$", re.MULTILINE)
# First inline `tests/...` code span anywhere in the file = the forcing-function test.
_TEST_RE = re.compile(r"`(tests/[^`]+)`")


def _field(pattern: re.Pattern, text: str, default: str = "-") -> str:
    m = pattern.search(text)
    return m.group(1).strip() if m else default


def _bug_files() -> list[Path]:
    files = [p for p in BUGS_DIR.glob("BUG-*.md") if _NUM_RE.search(p.name)]
    return sorted(files, key=lambda p: int(_NUM_RE.search(p.name).group(1)))


def render_index() -> str:
    rows = []
    for path in _bug_files():
        text = path.read_text(encoding="utf-8")
        bug_id = "BUG-" + _NUM_RE.search(path.name).group(1)
        title = _field(_TITLE_RE, text, default=path.stem)
        severity = _field(_SEVERITY_RE, text)
        status = _field(_STATUS_RE, text)
        test_m = _TEST_RE.search(text)
        forcing = f"`{test_m.group(1)}`" if test_m else "none"
        rows.append(f"| [{bug_id}]({path.name}) | {title} | {severity} | {status} | {forcing} |")

    lines = [
        "# Bug RCA Index",
        "",
        "> Generated by `tools/gen_bug_index.py` from the `BUG-*.md` files in this",
        "> directory - do not edit by hand. Run the generator after adding or editing a",
        "> bug; `tests/v2/test_bug_index_current.py` fails the build if this file is stale.",
        "> The README documents the convention and stays unchanged as bugs come and go.",
        "",
        "| ID | Title | Severity | Status | Forcing function |",
        "|----|-------|----------|--------|------------------|",
        *rows,
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    content = render_index()
    if "--check" in argv:
        current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if current.strip() != content.strip():
            print("bugs/INDEX.md is stale - run: python tools/gen_bug_index.py")
            return 1
        print("bugs/INDEX.md is up to date.")
        return 0
    INDEX_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {INDEX_PATH} ({len(_bug_files())} bugs).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
